# Generated by Django 5.2 on 2025-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
